# Generated by Django 5.2.1 on 2025-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('ordenado', 'Ordenado'), ('preparacion', 'En Preparación'), ('servido', 'Servido'), ('pagado', 'Pagado')], default='ordenado', max_length=100),
        ),
    ]
