# Generated by Django 5.2.1 on 2025-07-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlatoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dia')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plato')),
            ],
        ),
    ]
